name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build and commit the PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile cv
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Check pdf file
        run: |
          file main.pdf | grep -q ' PDF '

      - name: Upload file to repository
        run: |
          git config --global user.name "lwittrock"
          git config --global user.email "larwitt@gmx.de"
          git add main.pdf
          git commit -m "commit message"
          git push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'main.pdf'
          destination_repo: 'lwittrock/lwittrock.github.io'
          destination_folder: 'files'
          user_email: 'larwitt@gmx.de'
          user_name: 'lwittrock'
          commit_message: 'A custom message for the commit'
    
